DELETE http://localhost:3003/api/blogs/6505b1dfcc001c67e5047f7c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1dXAiLCJpZCI6IjY1MDViMTY3Y2MwMDFjNjdlNTA0N2Y3MCIsImlhdCI6MTY5NDg3MTk5Nn0.09jig-URjl4OHXUQ4DnHMoXgLOEM0oQKGdd9I0FNFrA