POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    
    "author": "sdfsdfsdfsdfsdfsd",
    "title": "Tesdfdfgdfgdfgsdfsdfsdstio",
    "url": "Url3sdsdfsfsdfsdff5555",
    "likes": 2000,
    "userId": "650457bed497a4a49fd1f459"
}